#!/usr/bin/env
"""THE PURPOSE OF THIS CODE IS TO GIVE BACK OUTPUT TO USER WHOM ASK FOR SPECIFIED ACTOR/ACTORS WITH GIVEN MOVIES"""
#dict_of_actors
#figure out why it keeps formatting weird
#Description, Actor/voice, IMDB Rating
print("Welcome to the top Listings of some of my Favorite Movie Actors")

#Informs player of decision based inuts needed
print("Please Chose from the selection of nominees:\n")

#directory of actors/actress with given movie and year it was introduced

dict1={"WillSmith": ["iRobot(2004)", "I Am Legend(2007)", "The Pursuti of Happiness(2006)"], 
"DenzelWashington":["Training Day(2001)", "Inside Man(2006)", "The Equalizer(2014)"], 
"IdrisElba": ["Takers(2010)", "The Losers(2010)", "Thor Ragnorak(2017)"],
"ChadwickBoseman-Rest in Paradise": ["Black Panther(2018)", "21 Bridges(2019)", "42(2013)"],
"MichaelBJordan": ["Creed(2015)", "Frustvale Station(2013)", "Without Remorse(2021)"],
"KevinHart": ["Ride Along(2014)", "Get Hard(2015)", "Jumanji(2019)"],
"DwayneJohnson": ["GridIron Gang(2006)", "Walking Tall(2004)", "The Rundown(2003)"]}
for i in dict1:
    print(i)
#Actors movie with Rating and quick synopsis
dict2 ={"iRobot":[7.1,"In 2035, highly intelligent robots fill public service positions throughout the dystopian world, operating under three rules to keep humans safe. Detective Del Spooner (Smith) investigates the alleged suicide of U.S. Robotics founder Alfred Lanning (Cromwell) and believes that a human-like robot called Sonny (Tudyk) murdered him."],
"I Am Legend": [7.2,"Robert Neville (Will Smith) is a scientist who was unable to stop the spread of the terrible virus that was incurable and man-made in this post-apocalyptic action thriller. Immune, Neville is now the last human survivor in what is left of New York City and perhaps the world. For three years, Neville has faithfully sent out daily radio messages, desperate to find any other survivors who might be out there. But he is not alone. Mutant victims of the plague - the Infected - lurk in the shadows - watching Neville's every move - waiting for him to make a fatal mistake. Perhaps mankind's last, best hope, Neville is driven by only one remaining mission: to find a way to reverse the effects of the virus using his own immune blood. But he knows he is outnumbered - and quickly running out of time"],
"The Pursuit of Happiness": [8.0, "Based on a true story about a man named Christopher Gardner. Gardner has invested heavily in a device known as a bone density scanner. He feels like he has it made selling these devices. However, they do not sell well as they are marginally better than x-ray at a much higher price. As Gardner works to make ends meet, his wife leaves him and he loses his apartment. Forced to live out in the streets with his son, Gardner continues to sell bone density scanners while concurrently taking on an unpaid internship as a stockbroker, with slim chances for advancement to a paid position. Before he can receive pay, he needs to outshine the competition through 6 months of training, and to sell his devices to stay afloat."],
"Training Day":[7.7, "In Los Angeles, a city where streets are overrun by drug dealers, those who have sworn to uphold the law are breaking them to clean up the streets. Denzel Washington plays L.A.P.D. detective Alonzo Harris, a veteran narcotics officer whose methods of enforcing the law are questionable, if not corrupt. 'Training Day' follows Harris as he trains rookie Jake Hoyt over a 24-hour period. Ethical dilemmas arise for Hoyt as well as the audience as questions present themselves as to whether or not Harris' methodology for ridding the streets of South Central Los Angeles of drugs is right or wrong."],
"Inside Man":[7.6, "Composed and meticulous, the soft-spoken and ingenious bank robber, Dalton Russell, has orchestrated the perfect heist--shortly, the Manhattan bank at the corner of Wall Street and Broadway along with dozens of hostages will be his to command. Try as he might, the rough hostage negotiator, Keith Frazier, is always one step behind the criminal mastermind--and what is more disheartening--the institution's silver-haired founder, Arthur Case, recruits the intelligent problem-fixer, Madeline White, to retrieve something of paramount importance. However, the thieves seem to procrastinate intentionally when they should be rushing into action. Will Arthur and Madeline get what they want this time?"],
"The Equalizer":[7.2, "Robert McCall is a former special service commando who faked his own death in hopes of living out a quiet life. Instead, he comes out of his self-imposed retirement to save a young girl and finds his desire for justice reawakened after coming face-to-face with members of a brutal Russian gang. McCall becomes the go-to man when the helpless require the kind of vengeance they would never find without his skills."],
"Takers":[6.2, "A seasoned team of bank robbers, including Gordon Jennings (Idris Elba), John Rahway (Paul Walker), A.J. (Hayden Christensen), and brothers Jake (Michael Ealy) and Jesse (Chris Brown) Attica successfully complete their latest heist and lead a life of luxury while planning their next job. When Ghost (Tip T.I. Harris), a former member of their team, is released from prison he convinces the group to strike an armored car carrying $20 million. As the Takers carefully plot their strategy and draw nearer to exacting the grand heist, a reckless police officer (Matt Dillon) inches closer to apprehending the criminals."],
"The Losers":[6.2, "A tale of double cross and revenge, centered upon the members of an elite U.S. Special Forces unit sent into the Bolivian jungle on a search and destroy mission. The team-Clay, Jensen, Roque, Pooch and Cougar -find themselves the target of a lethal betrayal instigated from inside by a powerful enemy known only as Max. Presumed dead, the group makes plans to even the score when they're joined by the mysterious Aisha, a beautiful operative with her own agenda. Working together, they must remain deep undercover while tracking the heavily-guarded Max, a ruthless man bent on embroiling the world in a new high-tech global war."],
"Thor Ragnorak":[7.9, "Imprisoned on the other side of the universe, the mighty Thor (Chris Hemsworth) finds himself in a deadly gladiatorial contest that puts him against The Incredible Hulk (Mark Ruffalo), his former ally and fellow Avenger. Thor's quest for survival leads him in a race against time to prevent the all-powerful Hela (Cate Blanchett) from destroying his home world and the Asgardian civilization."],
"Creed":[7.6, "Adonis Johnson is the son of the famous boxing champion Apollo Creed, who died in a boxing match in Rocky IV (1985). Adonis wasn't born until after his father's death and wants to follow his father’s footsteps in boxing. He seeks a mentor who is the former heavyweight boxing champion and former friend of Apollo Creed, the retired Rocky Balboa. Rocky eventually agrees to mentor Adonis. With Rocky's help they hope to get a title job to face even deadlier opponents than his father. But whether he is a true fighter remains to be seen...."],
"Fruitvale Station":[7.5, "This is the true story of Oscar Grant, a 22-year-old Bay Area resident who wakes up on the morning of December 31, 2008 and feels something in the air. Not sure what it is, he takes it as a sign to get a head start on his resolutions: being a better son to his mother, whose birthday falls on New Year's Eve, being a better partner to his girlfriend, who he hasn't been completely honest with as of late, and being a better father to T, their beautiful 4 year old daughter. He starts out well, but as the day goes on, he realizes that change is not going to come easy. He crosses paths with friends, family, and strangers, each exchange showing us that there is much more to Oscar than meets the eye. But it would be his final encounter of the day, with police officers at the Fruitvale BART station that would shake the Bay Area to its very core, and cause the entire nation to be witnesses to the story of Oscar Grant."],
"Without Remorse":[5.7, "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife in Tom Clancy's Without Remorse, the explosive origin story of action hero John Clark - one of the most popular characters in author Tom Clancy's Jack Ryan universe. When a squad of Russian soldiers kills his family in retaliation for his role in a top-secret op, Sr. Chief John Kelly (Michael B. Jordan) pursues the assassins at all costs. Joining forces with a fellow SEAL (Jodie Turner-Smith) and a shadowy CIA agent (Jamie Bell), Kelly's mission unwittingly exposes a covert plot that threatens to engulf the U.S. and Russia in an all-out war. Torn between personal honor and loyalty to his country, Kelly must fight his enemies without remorse if he hopes to avert disaster and reveal the powerful figures behind the conspiracy."],
"Black Panther":[7.3, "After the events of Captain America: Civil War, Prince T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new king. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war."],
"21 Bridges":[6.6, "Thrust into a citywide manhunt for a duo of cop killers, NYPD detective Andre Davis begins to uncover a massive conspiracy that links his fellow police officers to a criminal empire and must decide who he is hunting and who is hunting him. During the manhunt, Manhattan is completely locked down for the first time in its history - no exit or entry to the island including all 21 bridges."],
"42":[7.5, "In 1946, Jackie Robinson is a Negro League baseball player who never takes racism lying down. Branch Rickey is a Major League team executive with a bold idea. To that end, Rickey recruits Robinson to break the unspoken color line as the first modern African American Major League player. As both anticipate, this proves a major challenge for Robinson and his family as they endure unrelenting racist hostility on and off the field, from player and fan alike. As Jackie struggles against his nature to endure such abuse without complaint, he finds allies and hope where he least expects it."],
"Ride Along":[6.1, "Ben must prove he is good enough to date cop James' sister, so he volunteers to go on a Ride Along with him to show that he is not weak and will do whatever he must to get James' approval. But along the way, he runs into some obstacles that he must somehow overcome, and he finds very funny ways."],
"Get Hard":[6.0, "Kevin Hart plays the role of Darnell--a family man desperate to get enough money to buy a house in a better area to benefit his family's well-being. He is hired by James (Will Ferrell), a wimpy stock trader who is about to go to prison for 10 years, to prepare him for life behind bars. The catch is that James thinks Darnell is an ex-con--not because Darnell told him that, but because James just assumed."],
"Jumanji":[6.7, "The gang is back but the game has changed. As they return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored, from the arid deserts to the snowy mountains, to escape the world's most dangerous game."],
"The Rundown":[6.6, "In an attempt to earn enough money to start his own small business, the dauntless bounty hunter--or retrieval expert--and aspiring restaurateur, Beck, is talked into bringing back home his shady boss' adventure-seeking son, Travis, from the impenetrable Amazon jungle. However, there, in the dusty town of El Dorado, Beck is in for a wild ride, as the local tyrant and powerful mining baron, Cornelius Hatcher, too, is desperately trying to track down Travis: the only person who knows the exact location of a precious golden artefact. Now, the feisty barmaid with the hidden agenda, Mariana, and Hatcher's small army of whip-cracking gun-toting henchmen are after Beck and Travis, hell-bent on finding first the rare statuette. Will they get out of the jungle in one piece?"],
"Walking Tall":[6.2, "The hard-boiled former U.S. Special Forces veteran and decorated sergeant, Chris Vaughn, is in for a rude awakening, as his peaceful hometown has changed radically. With the old cedar mill gone out of business for good--and a garish gambling house opened instead, promoting drugs and violence thanks to his old high-school nemesis, Jay Hamilton--Chris will have no other choice but to take matters into his own hands as the town's new sheriff. Now, Jay's murderous henchmen have no place to hide--and with a primitive and lethally efficient four-by-four fence post as his weapon of choice--Chris is determined to clean up the vice and the corruption in his beloved birthplace. Who will dare to stop Chris, the furious one-man-army?"],
"GridIron Gang":[6.9, "In the Kilpatrick juvenile detention center, the supervisor and former football player Sean Porter sees the lack of discipline, self-esteem, union and perspective in the teenage interns and proposes to prepare a football team to play in one league. He is supported by his superiors and his successful experience changes the lives of many young kids."]}

dict3={"WillSmith":["Throughout life people will make you mad, disrespect you and treat you bad. Let God deal with the things they do, cause hate in your heart will consume you too."],
"Denzel Washington":["If I am a cup maker, I’m interested in making the best cup I possibly can. My effort goes into that cup, not what people think about it."],
"IdrisElba":["The English are good at bad guys - the James Bond-style villain, cunning, slow-burning. The Americans are much more obvious about it."],
"MichaelBJordan":["As human beings, why does it take somebody to feel like they're close to us for us to see their humanity? Why can't we see the humanity in people that are distant from us?"],
"ChadwickBoseman":["When you are deciding on next steps, next jobs, next careers, further education, you should rather find purpose than a job or a career,” he said at the time. “Purpose crosses disciplines. Purpose is an essential element of you. It is the reason you are on the planet at this particular time in history."],
"KevinHart":["Laughter heals all wounds, that’s one thing that everybody shares. No matter wat you’re going through, it makes you forget about your problems. I think the world should keep laughing."],
"DwayneJohnson":["The first step to achieving your goal, is to take a moment to respect your goal. Know what it means to you to achieve it."]}


#loop to keep player returning to list until ready to quit
while True: 
    #input to queue player for given actor/actress
    v1 = input("What actor would you like to see?\n")
    #Call to this dictionary to print inputed Actors Quote
    print(dict3[v1])
    #the q commando give player option to quit easily anytime during loop by pressing q
    if v1 == 'q':
        break
    #input pulling from directory of listed actors    
    for i in dict1[v1]:
        print(i)
    #input pulling from saved variables for actor and its directory of movies
    v2= input("what movie would you like to see?\n")
    if v2 == 'q':
        break
    #input pulling from respected directories will loop back to first question unitl command to 'quit' is input    
    v3= int(input("What accesory would you like to see [0]IMDb Rating, [1]Description?\n"))
    print(dict2[v2][v3])
